[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python bot_runner.py webhook"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = { 
    BOT_MODE = "webhook", 
    WEBHOOK_ENABLED = "true", 
    DATABASE_TYPE = "postgresql",
    DATABASE_URL = "${{Postgres.DATABASE_URL}}",
    POSTGRES_HOST = "${{Postgres.POSTGRES_HOST}}",
    POSTGRES_PORT = "${{Postgres.POSTGRES_PORT}}",
    POSTGRES_DB = "${{Postgres.POSTGRES_DB}}",
    POSTGRES_USER = "${{Postgres.POSTGRES_USER}}",
    POSTGRES_PASSWORD = "${{Postgres.POSTGRES_PASSWORD}}"
}

[environments.development]
variables = { 
    BOT_MODE = "polling", 
    DEBUG_MODE = "true", 
    DATABASE_TYPE = "postgresql",
    DATABASE_URL = "${{Postgres.DATABASE_URL}}",
    POSTGRES_HOST = "${{Postgres.POSTGRES_HOST}}",
    POSTGRES_PORT = "${{Postgres.POSTGRES_PORT}}",
    POSTGRES_DB = "${{Postgres.POSTGRES_DB}}",
    POSTGRES_USER = "${{Postgres.POSTGRES_USER}}",
    POSTGRES_PASSWORD = "${{Postgres.POSTGRES_PASSWORD}}"
}

# Railway PostgreSQL service configuration
[[services]]
name = "optrixtrades-bot"
source = "."

[[services]]
name = "postgres"
image = "postgres:15"
variables = { POSTGRES_DB = "optrixtrades", POSTGRES_USER = "optrixtrades_user" }